spring.application.name=shop-web

# Configuracion de la conexion a la BBDD
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysqldb://localhost:3306/shop_web}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.datasource-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
# Cuando se crea la bbdd y se ejecuta por primera vez, se debe de poner "create"
# Una vez se crea la tabla de forma automatica con el "create" se cambia por un "update" para que insertar los datos y que no se sobreescriban
spring.jpa.hibernate.ddl-auto=create

jwt.expiration=86400000 
